### ISSUE TITLE
Obelisk API reference?

### ISSUE THREAD

**Issue by dmp1ce** [Akeboshiwind/obelisk-ui#1]
Did you use a reference when putting together this project? I'm interested in monitoring the Obelisk miners from Haskell.

**Comment by Akeboshiwind** [comment]
Sorry to say but I couldn't find a reference when I was making this. All I
did was to navigate the panel with the network tab open in Chrome and note
down what was called and what was returned.

**Comment by mindjuice** [comment]
This is the doc I started for the Gen 1 Obelisk API.  It's not complete, but should help.  The API endpoints are mostly the same in Gen 2 Obelisks, but the responses are different in some cases.  Haven't had time to update this for either generation:

    https://gitlab.com/NebulousLabs/obelisk-ob1/blob/master/src/apiserver/api-docs.md

You can hit any of the endpoints described in the above doc when logged in and see what comes back.

**Comment by Akeboshiwind** [comment]
I'm going to close this issue as there seems to be nothing more to add :)
